apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: EMAIL_USER
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: EMAIL_USER
             - name: EMAIL_PASS
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: EMAIL_PASS
             - name: ACCESS_TOKEN_SECRET
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: ACCESS_TOKEN_SECRET
             - name: REFRESH_TOKEN_SECRET
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: REFRESH_TOKEN_SECRET
             - name: GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: GOOGLE_CLIENT_ID
             - name: GOOGLE_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: GOOGLE_CLIENT_SECRET
             - name: GOOGLE_REDIRECT_URL
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: GOOGLE_REDIRECT_URL
             - name: GITHUB_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: GITHUB_CLIENT_ID
             - name: GITHUB_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: GITHUB_CLIENT_SECRET
             - name: GITHUB_REDIRECT_URL
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: GITHUB_REDIRECT_URL
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: auth-service-production-config-secret
                   key: DATABASE_URL
